"""
PSD Rename Worker — 通过 ExtendScript 驱动 Photoshop 批量重命名 PSD 图层

处理流程:
  1. 收集隐藏图层 ID（处理前快照）
  2. 解锁所有图层
  3. 删除隐藏/空白图层
  4. 应用图层蒙版
  5. 解散所有组（可选）
  6. 跳过无文本层 PSD（可选）
  7. 按类型重命名 + 栅格化
  8. 另存到输出目录

命名规则:
  TEXT                          → text / text1, text2 ...
  SHAPE/FILL + 覆盖 ≥80% 画布   → frame
  SHAPE/FILL（其余）             → name_shape / name_shape1 ...
  PIXEL / SMART OBJECT          → name_pixel（不编号）
"""
import os
import re
import time
import subprocess
import tempfile
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

DEFAULT_TYPE_RULES = {
    "pixel": "scenebg",
    "smart": "scenebg",
    "shape": "stickerbg",
    "frame": "frame",
}


# ── JSX 生成 ────────────────────────────────────────────────────────────────

def build_rename_jsx(
    psd_paths: list[str],
    output_folder: str,
    name_pixel: str = "scenebg",
    name_shape: str = "stickerbg",
    jsx_log_path: str = "/tmp/psd_rename.log",
    delete_hidden: bool = True,
    skip_no_text: bool = True,
    flatten_groups: bool = True,
) -> str:
    """生成 Photoshop ExtendScript 代码。"""
    name_smart = name_pixel
    name_frame = "frame"

    # Build JS array of absolute PSD paths
    paths_js = ",\n".join(f'  new File("{p.replace(chr(92), "/")}")'
                          for p in psd_paths)
    output_folder_js = output_folder.replace("\\", "/")
    log_path_js = jsx_log_path.replace("\\", "/")

    delete_hidden_js = "true" if delete_hidden else "false"
    skip_no_text_js = "true" if skip_no_text else "false"
    flatten_groups_js = "true" if flatten_groups else "false"

    return f"""// Auto-generated by Imagen Studio PSD Rename Worker
#target photoshop
app.displayDialogs = DialogModes.NO;

var NAME_TEXT  = "text";
var NAME_PIXEL = "{name_pixel}";
var NAME_SMART = "{name_smart}";
var NAME_SHAPE = "{name_shape}";
var NAME_FRAME = "{name_frame}";
var DELETE_HIDDEN   = {delete_hidden_js};
var SKIP_NO_TEXT    = {skip_no_text_js};
var FLATTEN_GROUPS  = {flatten_groups_js};

var OUTPUT_FOLDER = new Folder("{output_folder_js}");
var LOG_FILE      = new File("{log_path_js}");

var psdFiles = [
{paths_js}
];

function jsxLog(msg) {{
    LOG_FILE.open("a");
    LOG_FILE.writeln(msg);
    LOG_FILE.close();
}}

// Numeric LayerKind values (enum names deprecated in PS 2025)
var K_TEXT   = 2;
var K_NORMAL = 1;
var K_SMART  = 17;
var K_SHAPE  = 7;
try {{ K_TEXT   = LayerKind.TEXT;        }} catch(e) {{}}
try {{ K_NORMAL = LayerKind.NORMAL;      }} catch(e) {{}}
try {{ K_SMART  = LayerKind.SMARTOBJECT; }} catch(e) {{}}
try {{ K_SHAPE  = LayerKind.SHAPE;       }} catch(e) {{}}

var g_workDoc    = null;
var g_frameCache = {{}};

// ── Frame detection ───────────────────────────────────────────────────────
function isFrameStyleLayer(layer) {{
    if (!g_workDoc) return false;
    if (g_frameCache.hasOwnProperty(layer.id)) return g_frameCache[layer.id];
    var result = false;
    try {{
        var k  = null;
        try {{ k = layer.kind; }} catch(e) {{}}
        var ks = "" + k;
        if (k === K_TEXT   || k === 2  || ks === "LayerKind.TEXT")        {{ g_frameCache[layer.id] = false; return false; }}
        if (k === K_SMART  || k === 17 || ks === "LayerKind.SMARTOBJECT") {{ g_frameCache[layer.id] = false; return false; }}
        if (k === K_NORMAL || k === 1  || ks === "LayerKind.NORMAL")      {{ g_frameCache[layer.id] = false; return false; }}
        var bounds = layer.bounds;
        var w = +bounds[2] - +bounds[0];
        var h = +bounds[3] - +bounds[1];
        var docW = +g_workDoc.width;
        var docH = +g_workDoc.height;
        result = (w >= docW * 0.8 && h >= docH * 0.8);
        jsxLog("frame_check|" + layer.name + "|" + Math.round(w) + "x" + Math.round(h) + "/" + Math.round(docW) + "x" + Math.round(docH) + "|" + result);
    }} catch(e) {{
        jsxLog("frame_check_err|" + layer.name + "|" + e.message);
    }}
    g_frameCache[layer.id] = result;
    return result;
}}

function getBaseName(layer) {{
    var k  = null;
    try {{ k = layer.kind; }} catch(e) {{}}
    var ks = "" + k;
    if (k === K_TEXT   || k === 2  || ks === "LayerKind.TEXT")        return NAME_TEXT;
    if (isFrameStyleLayer(layer))                                      return NAME_FRAME;
    if (k === K_SMART  || k === 17 || ks === "LayerKind.SMARTOBJECT") return NAME_SMART;
    if (k === K_NORMAL || k === 1  || ks === "LayerKind.NORMAL")      return NAME_PIXEL;
    return NAME_SHAPE;
}}

// ── Visibility helpers ────────────────────────────────────────────────────
function getAMVisible(layer) {{
    try {{
        var ref = new ActionReference();
        ref.putIdentifier(charIDToTypeID("Lyr "), layer.id);
        var desc = executeActionGet(ref);
        return desc.getBoolean(stringIDToTypeID("visible"));
    }} catch(e) {{
        return layer.visible;
    }}
}}

function isHidden(layer) {{
    try {{ if (!layer.visible)      return true; }} catch(e) {{}}
    try {{ if (!getAMVisible(layer)) return true; }} catch(e) {{}}
    try {{ if (layer.opacity    === 0) return true; }} catch(e) {{}}
    try {{ if (layer.fillOpacity === 0) return true; }} catch(e) {{}}
    return false;
}}

// ── Collect hidden IDs before any changes ─────────────────────────────────
function collectHiddenIds(layerSet, hiddenIds) {{
    for (var i = 0; i < layerSet.artLayers.length; i++) {{
        try {{
            var l = layerSet.artLayers[i];
            if (!l.visible || !getAMVisible(l) || l.opacity === 0 || l.fillOpacity === 0) {{
                hiddenIds[l.id] = true;
                continue;
            }}
            // Also mark empty pixel layers (bounds = 0)
            try {{
                var lk = null; try {{ lk = l.kind; }} catch(e) {{}}
                var lks = "" + lk;
                if (lk !== K_TEXT && lk !== 2 && lks !== "LayerKind.TEXT") {{
                    var b = l.bounds;
                    if ((b[2]-b[0]) == 0 && (b[3]-b[1]) == 0) {{ hiddenIds[l.id] = true; }}
                }}
            }} catch(e) {{}}
        }} catch(e) {{}}
    }}
    for (var j = 0; j < layerSet.layerSets.length; j++) {{
        try {{
            var grp = layerSet.layerSets[j];
            if (!grp.visible || !getAMVisible(grp)) {{
                hiddenIds["grp_" + grp.name] = true;
            }} else {{
                collectHiddenIds(grp, hiddenIds);
            }}
        }} catch(e) {{}}
    }}
}}

// ── Unlock all ────────────────────────────────────────────────────────────
function unlockAll(layerSet) {{
    for (var i = 0; i < layerSet.artLayers.length; i++) {{
        var l = layerSet.artLayers[i];
        try {{ if (l.isBackgroundLayer) l.isBackgroundLayer = false; }} catch(e) {{}}
        try {{ l.allLocked         = false; }} catch(e) {{}}
        try {{ l.pixelsLocked      = false; }} catch(e) {{}}
        try {{ l.positionLocked    = false; }} catch(e) {{}}
        try {{ l.transparencyLocked = false; }} catch(e) {{}}
    }}
    for (var j = 0; j < layerSet.layerSets.length; j++) {{
        try {{ layerSet.layerSets[j].allLocked = false; }} catch(e) {{}}
        unlockAll(layerSet.layerSets[j]);
    }}
}}

// ── Delete hidden layers by pre-collected IDs ─────────────────────────────
function deleteHiddenById(layerSet, hiddenIds) {{
    for (var i = layerSet.artLayers.length - 1; i >= 0; i--) {{
        try {{
            var l = layerSet.artLayers[i];
            if (hiddenIds[l.id]) {{
                jsxLog("delete_hidden|" + l.name);
                try {{ l.remove(); }} catch(e) {{}}
            }}
        }} catch(e) {{}}
    }}
    for (var j = layerSet.layerSets.length - 1; j >= 0; j--) {{
        try {{
            var grp = layerSet.layerSets[j];
            if (hiddenIds["grp_" + grp.name]) {{
                jsxLog("delete_hidden_group|" + grp.name);
                try {{ grp.remove(); }} catch(e) {{}}
            }} else {{
                deleteHiddenById(grp, hiddenIds);
            }}
        }} catch(e) {{}}
    }}
}}

// ── Apply pixel masks ─────────────────────────────────────────────────────
function hasMask(layer) {{
    try {{
        var ref = new ActionReference();
        ref.putIdentifier(charIDToTypeID("Lyr "), layer.id);
        var desc = executeActionGet(ref);
        return desc.hasKey(stringIDToTypeID("userMaskEnabled"));
    }} catch(e) {{ return false; }}
}}

function applyMaskAction() {{
    var desc = new ActionDescriptor();
    var ref  = new ActionReference();
    ref.putEnumerated(charIDToTypeID("Chnl"), charIDToTypeID("Chnl"), charIDToTypeID("Msk "));
    desc.putReference(charIDToTypeID("null"), ref);
    desc.putBoolean(charIDToTypeID("Aply"), true);
    executeAction(charIDToTypeID("Dlt "), desc, DialogModes.NO);
}}

function applyAllMasks(layerSet) {{
    for (var i = layerSet.artLayers.length - 1; i >= 0; i--) {{
        try {{
            var l = layerSet.artLayers[i];
            if (!hasMask(l)) continue;
            var lk = null; try {{ lk = l.kind; }} catch(e) {{}}
            var lks = "" + lk;
            if (lk !== K_NORMAL && lk !== 1 && lks !== "LayerKind.NORMAL") continue;
            app.activeDocument.activeLayer = l;
            applyMaskAction();
            jsxLog("mask_applied|" + l.name);
        }} catch(e) {{}}
    }}
    for (var j = 0; j < layerSet.layerSets.length; j++) {{
        try {{ applyAllMasks(layerSet.layerSets[j]); }} catch(e) {{}}
    }}
}}

// ── Ungroup all ───────────────────────────────────────────────────────────
function ungroupLayerSet(grp) {{
    while (grp.layerSets.length > 0) {{ ungroupLayerSet(grp.layerSets[0]); }}
    while (grp.artLayers.length > 0) {{
        try {{ grp.artLayers[0].move(grp, ElementPlacement.PLACEBEFORE); }} catch(e) {{ break; }}
    }}
    try {{ grp.remove(); }} catch(e) {{}}
}}

function ungroupAll(layerSet) {{
    var groups = [];
    for (var j = 0; j < layerSet.layerSets.length; j++) {{ groups.push(layerSet.layerSets[j]); }}
    for (var k = 0; k < groups.length; k++) {{
        try {{ ungroupLayerSet(groups[k]); }} catch(e) {{ jsxLog("ungroup_err|" + e.message); }}
    }}
}}

// ── Has text layers ───────────────────────────────────────────────────────
function hasTextLayers(layerSet) {{
    for (var i = 0; i < layerSet.artLayers.length; i++) {{
        try {{
            var lk = null; try {{ lk = layerSet.artLayers[i].kind; }} catch(e) {{}}
            var lks = "" + lk;
            if (lk === K_TEXT || lk === 2 || lks === "LayerKind.TEXT") return true;
        }} catch(e) {{}}
    }}
    for (var j = 0; j < layerSet.layerSets.length; j++) {{
        try {{ if (hasTextLayers(layerSet.layerSets[j])) return true; }} catch(e) {{}}
    }}
    return false;
}}

// ── Count layers per base name ────────────────────────────────────────────
function countVisible(layerSet, counts) {{
    for (var i = 0; i < layerSet.artLayers.length; i++) {{
        var b = getBaseName(layerSet.artLayers[i]);
        counts[b] = (counts[b] || 0) + 1;
    }}
    for (var j = 0; j < layerSet.layerSets.length; j++) {{
        countVisible(layerSet.layerSets[j], counts);
    }}
}}

// ── Rename one layer ──────────────────────────────────────────────────────
function renamePSDLayer(layer, counters, totalCounts) {{
    var base = getBaseName(layer);
    if (!counters[base]) counters[base] = 1;
    var n = counters[base]++;
    // pixel/smart (scenebg) — never numbered
    if (base === NAME_PIXEL || base === NAME_SMART) return base;
    // frame — never numbered (assume one per PSD)
    if (base === NAME_FRAME) return base;
    // text, stickerbg — numbered only when multiple
    if (totalCounts[base] > 1) return base + n;
    return base;
}}

function renameLayers(layerSet, counters, totalCounts) {{
    for (var i = 0; i < layerSet.artLayers.length; i++) {{
        try {{
            var layer = layerSet.artLayers[i];
            var lk = null; try {{ lk = layer.kind; }} catch(e) {{}}
            var lks = "" + lk;
            var isText = (lk === K_TEXT || lk === 2 || lks === "LayerKind.TEXT");
            var newName = renamePSDLayer(layer, counters, totalCounts);
            jsxLog("rename|" + layer.name + "|" + newName + "|" + lks);
            layer.name = newName;
            if (!isText) {{
                try {{ layer.rasterize(RasterizeType.ENTIRELAYER); }} catch(e) {{}}
                try {{
                    if (hasMask(layer)) {{
                        app.activeDocument.activeLayer = layer;
                        applyMaskAction();
                    }}
                }} catch(me) {{}}
            }}
        }} catch(e) {{ jsxLog("rename_err|" + e.message); }}
    }}
    for (var j = 0; j < layerSet.layerSets.length; j++) {{
        try {{ renameLayers(layerSet.layerSets[j], counters, totalCounts); }} catch(e) {{}}
    }}
}}

// ── Process one PSD ───────────────────────────────────────────────────────
function processPSD(file) {{
    jsxLog("opened|" + file.name);
    var doc = null;
    var wasAlreadyOpen = false;
    for (var d = 0; d < app.documents.length; d++) {{
        try {{
            if (app.documents[d].fullName.toString() === file.fullName.toString()) {{
                doc = app.documents[d];
                wasAlreadyOpen = true;
                break;
            }}
        }} catch(e) {{}}
    }}
    if (!doc) {{
        try {{ doc = app.open(file); }} catch(e) {{
            jsxLog("error|" + file.name + "|" + e.message);
            return;
        }}
    }}

    var workDoc = doc;
    if (wasAlreadyOpen) {{
        try {{ workDoc = doc.duplicate(file.name, false); }}
        catch(e) {{ wasAlreadyOpen = false; }}
    }}

    try {{
        // Step 1: snapshot hidden state
        var hiddenIds = {{}};
        if (DELETE_HIDDEN) collectHiddenIds(workDoc, hiddenIds);

        // Step 2: unlock all
        unlockAll(workDoc);

        // Step 3: delete hidden
        if (DELETE_HIDDEN) deleteHiddenById(workDoc, hiddenIds);

        // Step 4: apply masks
        applyAllMasks(workDoc);

        // Step 5: ungroup
        if (FLATTEN_GROUPS) ungroupAll(workDoc);

        // Step 6: skip if no text
        if (SKIP_NO_TEXT && !hasTextLayers(workDoc)) {{
            jsxLog("skipped|" + file.name + "|no text layers");
            return;
        }}

        // Step 7: rename + rasterize
        g_workDoc    = workDoc;
        g_frameCache = {{}};
        var totalCounts = {{}};
        countVisible(workDoc, totalCounts);
        var counters = {{}};
        renameLayers(workDoc, counters, totalCounts);

        // Step 8: save
        if (!OUTPUT_FOLDER.exists) OUTPUT_FOLDER.create();
        var outFile = new File(OUTPUT_FOLDER.fullName + "/" + file.name);
        var opts = new PhotoshopSaveOptions();
        opts.layers            = true;
        opts.embedColorProfile = true;
        opts.annotations       = false;
        opts.alphaChannels     = true;
        opts.spotColors        = true;
        try {{
            workDoc.saveAs(outFile, opts, true);
            jsxLog("saved|" + file.name + "|" + outFile.fullName);
        }} catch(e) {{
            try {{ workDoc.saveAs(outFile, opts, false); jsxLog("saved|" + file.name + "|" + outFile.fullName); }}
            catch(e2) {{ jsxLog("error|" + file.name + "|" + e2.message); }}
        }}
    }} finally {{
        try {{ workDoc.close(SaveOptions.DONOTSAVECHANGES); }} catch(e) {{}}
    }}
}}

// ── Main ──────────────────────────────────────────────────────────────────
jsxLog("started|" + psdFiles.length + " files");
if (!OUTPUT_FOLDER.exists) OUTPUT_FOLDER.create();
for (var k = 0; k < psdFiles.length; k++) {{
    processPSD(psdFiles[k]);
}}
jsxLog("done|" + psdFiles.length + " files processed");
"""


# ── Photoshop 执行 ──────────────────────────────────────────────────────────

def _find_photoshop_app_name() -> str:
    """查找本机安装的 Photoshop 应用名。"""
    try:
        result = subprocess.run(
            ["mdfind", "kMDItemCFBundleIdentifier == 'com.adobe.Photoshop'"],
            capture_output=True, text=True, timeout=10,
        )
        for path in result.stdout.strip().splitlines():
            if path.endswith(".app"):
                name = os.path.basename(path).replace(".app", "")
                if "Photoshop" in name:
                    return name
    except Exception:
        pass
    return "Adobe Photoshop"


def run_photoshop_jsx(jsx_code: str, jsx_log_path: str) -> subprocess.Popen:
    """
    将 JSX 写入临时文件，用 osascript 驱动 Photoshop 执行。
    返回 Popen 句柄供调用方轮询。
    """
    jsx_path = os.path.join(tempfile.gettempdir(), "imagen_psd_rename.jsx")
    Path(jsx_path).write_text(jsx_code, encoding="utf-8")
    Path(jsx_log_path).write_text("", encoding="utf-8")  # clear log

    jsx_loader = (
        f"var _f=new File('{jsx_path}');"
        "_f.open('r');var _s=_f.read();_f.close();eval(_s);"
    )
    ps_app = _find_photoshop_app_name()
    logger.info("[psd_rename] Photoshop app: %s", ps_app)

    apple_script = (
        f'tell application "{ps_app}"\n'
        f'    activate\n'
        f'    delay 2\n'
        f'    do javascript "{jsx_loader}"\n'
        f'end tell'
    )
    as_path = os.path.join(tempfile.gettempdir(), "imagen_psd_rename.applescript")
    Path(as_path).write_text(apple_script, encoding="utf-8")

    process = subprocess.Popen(
        ["osascript", as_path],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    logger.info("[psd_rename] osascript launched, pid=%s", process.pid)
    return process


# ── 日志解析 ────────────────────────────────────────────────────────────────

# Log line format (pipe-delimited):
#   opened|filename.psd
#   saved|filename.psd|/full/path.psd
#   skipped|filename.psd|reason
#   error|filename.psd|reason
#   rename|old_name|new_name|kind
#   started|N files
#   done|N files processed

_LOG_RE = re.compile(r"^(opened|saved|skipped|error|started|done)\|(.+)$")


def parse_jsx_log(log_path: str, last_offset: int = 0) -> tuple[list[dict], int]:
    """
    增量读取 JSX log 文件，返回 (事件列表, 新 offset)。

    事件 dict 结构:
        {"type": "saved"|"skipped"|"error"|"opened"|"done",
         "filename": "xxx.psd",
         "message": "..."}
    """
    events: list[dict] = []
    try:
        content = Path(log_path).read_text(encoding="utf-8", errors="replace")
    except FileNotFoundError:
        return events, last_offset

    new_lines = content[last_offset:]
    new_offset = last_offset + len(new_lines)

    for raw_line in new_lines.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        m = _LOG_RE.match(line)
        if not m:
            continue
        event_type = m.group(1)
        rest = m.group(2).split("|")
        filename = rest[0] if rest else ""
        message = rest[1] if len(rest) > 1 else ""
        events.append({"type": event_type, "filename": filename, "message": message})

    return events, new_offset
